"""
Django settings for cfehome project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import environ
from pathlib import Path
from .juzzmin import JAZZMIN_UI_TWEAKS

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p&5(p4(z+bie5p1f%p33!z%cy%jeo6qsu)tah!&0ljs#!@*9tz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

print(DEBUG)

ALLOWED_HOSTS = ['.railway.app', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'authuser',
    'dashboard'
   
]

AUTH_USER_MODEL = 'authuser.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cfehome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cfehome.wsgi.application'


DATABASES = {
  'default': {
     'ENGINE': 'django.db.backends.postgresql',
     'NAME': 'fundhancedb2',
     'USER': 'fundhancedb_owner',
     'PASSWORD': 'RdirsP5hN2kc',
     'HOST': 'ep-round-bird-a2n4c50k.eu-central-1.aws.neon.tech',
     'PORT':  5432,
     'OPTIONS': {
       'sslmode': 'require',
     },
  }
 }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR.parent / "local-cdn" / "static"

STATICFILES_DIRS = [
    # "/Users/cfe/Dev/django-tailwindcss/src/static",
    BASE_DIR / "static"
]

if not os.path.isdir(STATIC_ROOT):
    os.makedirs(STATIC_ROOT, mode=0o755)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_STORAGE = ('whitenoise.storage.CompressedManifestStaticFilesStorage')
CSRF_TRUSTED_ORIGINS = ['https://fundhance-demo.up.railway.app']

STRIPE_PUBLISHABLE_KEY = "pk_test_51PCS3dC44EYDQ7lQlWRCEm6PHnhlEOU5qr7Ws1ZnpxzfhQHQ2ds42m7A8ILGGu93Nef3DE3qzHOIVL1EGbIV2v2100OSVwBtHh"
STRIPE_SECRET_KEY = "sk_test_51PCS3dC44EYDQ7lQut4XcdtcdPPJjJQxIGdUMBXCR6Mzi99LYgQaEEbK1d4qJ7MRG2L2sDqyYV7dEMTGzenSLEdr00IuHin3jX"
STRIPE_ENDPOINT_SECRET = ""
STRIPE_WEBHOOK_SECRET = "whsec_8290ee95064fd8c6a722fe8ab547eab6635040e9ac25e2dda15fef457b9b245d"


JAZZMIN_UI_TWEAKS = JAZZMIN_UI_TWEAKS


#REDIRECT_DOMAIN = 'http://127.0.0.1:8000'
REDIRECT_DOMAIN =  'https://fundhance-demo.up.railway.app/account_overview/'
